# LLM => LLAMA, GEMINI, COHERE, MISTRAL

LLM_MODELS:

  LLAMA:
    modelName: "llama-3.3-70b-versatile"

  MISTRAL:
    mistral_1: "ministral-8b-latest"
    mistral_2: "mistral-small-latest"

  GEMINI:
    gemini: "gemini-2.5-flash-lite"
  
  COHERE: 
    cohere: "command-r-08-2024"
    cohere2: "command-a-03-2025"

  OPEN_ROUTER:
    GPT: "openai/gpt-oss-120b:free"

EMBEDDING_MODELS:
  Huggingface:
    huggingface_model: "sentence-transformers/all-MiniLM-L6-v2"

TTS_ENGINE:
  VOICE_ID: "JBFqnCBsd6RMkjVDRZzb"
  MODEL_ID: "eleven_multilingual_v2"
  OUTPUT_FORMAT: "mp3_44100_128"